### ISSUE TITLE
[REGRESSION] Speed falling, small number of peers

### ISSUE THREAD

**Issue by thermatk** [mafintosh/torrent-stream#106]
Somewhere between 0.12 and 0.13.1 happened a change that affected torrent-stream forever. Since the 0.13 release speed dramatically fell, peers are not discovered in quantities enough to download as fast as torrent-stream did before.
I have a very simple test for it - I build peerflix 0.29.1 as is and compare it with the same peerflix using torrent-stream 0.12. I tried to get the exact commit that caused it, but the fact is that between https://github.com/mafintosh/torrent-stream/commit/7666f34aebb94645bbaf44feba0c078508dbdf7d
and https://github.com/mafintosh/torrent-stream/commit/078b812cf300bfc01f454020daa19d9caf5e8ae3 peerflix doesn't work at all(before - great speed, after - works but slowly). Affects on Linux and Windows, shouldn't be platform-specific.
What can we do? :)

**Comment by asapach** [comment]
I've been using 0.13 for several months now and I didn't notice any dramatic difference. Can you back it up by some concrete numbers? Back-to-back comparison?

**Comment by thermatk** [comment]
It's more visible with torrents that don't have thousands of peers, somehow torrent-stream blocks or ignors a lot of them, so if there aren't many it becomes slow or even unusable at 0 kb/s

**Comment by thermatk** [comment]
So
A random IT Crowd magnet: magnet:?xt=urn:btih:99d25bb98b1931001f7f5bc560be717f653bd551&dn=The.IT.Crowd.Season.2&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
You can see that new torrent-stream downloaded only a half of what the old did and actually the old found the same three peers immediately and the new one was searching for 17s
![2015-03-29 18 06 36](https://cloud.githubusercontent.com/assets/2287483/6886249/d566963c-d63e-11e4-82b1-ec406a21dcf1.png)
![2015-03-29 18 06 46](https://cloud.githubusercontent.com/assets/2287483/6886250/d566fb72-d63e-11e4-82ed-623dacb3a612.png)
![2015-03-29 18 07 26](https://cloud.githubusercontent.com/assets/2287483/6886251/d567507c-d63e-11e4-9889-825c9adf1a87.png)
![2015-03-29 18 07 46](https://cloud.githubusercontent.com/assets/2287483/6886248/d565b6a4-d63e-11e4-89aa-1147d70929b2.png)

**Comment by thermatk** [comment]
Update: I am completely misunderstanding how it works, may be there are two problems at once. But After 0.13.0 speed of finding peers initially is lower but once they are found everything is alright, after 0.14.0 it's a disaster
0.12.0 best one
0.13.0-0.14.0 - slow
0.14.1 and afterwards - even worse

**Comment by thermatk** [comment]
peerflix 0.22 with torrent-stream 0.18.0 with very old bittorrent-dht 1.5.0 is working great! Found the cause!

**Comment by thermatk** [comment]
bittorrent-dht 3.0.0 is not affected
Hooray!

**Comment by thermatk** [comment]
I've sent a pull-request. But looking at the repo there might be some API breakage, please look into it, I don't understand how the whole thing works that deep :)
https://github.com/feross/bittorrent-dht/commit/920dee18759118257700bbc30c3944a9446097fe
