### ISSUE TITLE
Pulse to prevent flooding.

### ISSUE THREAD

**Issue by dcerisano** [mafintosh/torrent-stream#120]
Seem to have an early swarm-level solution for network flooding. Just a one-liner in the selector.

Requests to peers are prevented above a threshold swarm download rate (PULSE), and resumed below the threshold, producing a _pulse_ in the network, rather than a flood (see fig 1).

FLOOD allows a limited flood before pulsing begins.

```
engine.PULSE = Number.MAX_SAFE_INTEGER;  // Defaults: do not pulse
engine.FLOOD = Number.MAX_SAFE_INTEGER;  

var select = function(wire, hotswap) {
   // Pulse
   if (swarm.downloaded > engine.FLOOD && swarm.downloadSpeed() > engine.PULSE) 
       return true;
   ...
```

Default is no pulsing (existing behavior). The flood limit and pulse threshold can be set dynamically by a torrent-stream _consumer_.

For example in a request for a video segment:

```
engine.FLOOD = 10  * 1024 * 1024 + engine.swarm.downloaded; //  10 MB flood
engine.PULSE = 312 * 1024;                                  // 312 KBps pulse (720p)
```

![image](https://cloud.githubusercontent.com/assets/1641613/8485040/ef626316-20c8-11e5-9b90-fbf72b4dede2.png)

**Comment by bsuh** [comment]
Wow this is very nice! Thanks for this. :+1:

**Comment by dcerisano** [comment]
- Note this does not limit to an upper rate, rather it seeks a lower limit.
- Since pieces are known to be 16K in size, limiting the number of onrequest calls would be the way to set an upper limit on a healthy (predictable) torrent.
- The issue with achieving a hard upper limit is that freeriders (leeches)  weaken the torrent and make the algorithm unpredictable.
- This method ensures at least a lower limit can be maintained.

Since pieces are known to be 16K in size, limiting the number of onrequest calls is the way to set an upper limit.
The issue with achieving a hard upper limit is overcoming freeriders (leeches) that weaken the torrent and make the algorithm unpredictable.
This method ensures at least a lower limit can be maintained.

**Comment by dcerisano** [comment]
Growling good. Flooding bad.

**Comment by rstanislav** [comment]
Is there any way to make this dynamic ? ie when starting download speed limited at ~ 50mbps, when user watching and not doing any seek it limit to file bitrate + 10% - so it uses only needed amount of BW, when user seek's to some point - it again gives full speed (50mbps) and then again after first few pieces downloaded it limits speed to file bitrate + 10% ?

**Comment by dcerisano** [comment]
It is dynamic. The stream consumer (a video app in your case?) can set rate at any time, as described.
The torrent-stream has no way to know how fast the stream is being consumed.
It has to be done at the consumer level where that info is available.
