### ISSUE TITLE
Torrent 'ready' event not fired

### ISSUE THREAD

**Issue by herlon214** [mafintosh/torrent-stream#121]
Anyone can tell me why the 'ready' event isn't firing sometimes?

**Comment by bsuh** [comment]
Are you attaching an event handler to the event right after the engine is created? If it has already fired, it won't fire again when you attach an event handler later. If you just need some code to run after 'ready', use `engine.ready()`

**Comment by herlon214** [comment]
Yeah @bsuh, this was the problem. Thanks!
