### ISSUE TITLE
Specific file selection grabbing more file than expected

### ISSUE THREAD

**Issue by zoo1** [mafintosh/torrent-stream#131]
engine.on('ready', function () {
    			engine.files.forEach(function (file){
    			if(file.name === singlefile)
    			{
    				file.select()
    				console.log(file.name)
    			}
    			else
    				file.deselect()
I am running the above code, and the torrent seems to be grabbing files outside of desired single file I have selected. Is there an issue with my code of is this a bug?

**Comment by asapach** [comment]
This is how bittorrent works: all the files in a torrent are stored as a continuous array of bytes split into a lot of pieces of the same size. Piece size varies from 32KB to several MB. There can more than one file in a single piece. So when you do `file.select()` it actually downloads all the pieces that comprise that particular file, and if it overlaps with other files, some of them (or some of their parts) will be downloaded as well.

**Comment by zoo1** [comment]
Thanks for the clarification.
