### ISSUE TITLE
"cb() is not a function" on engine.remove

### ISSUE THREAD

**Issue by giacomocerquone** [mafintosh/torrent-stream#143]
Hello, so I'm trying to call engine.remove() once the engine is created and it's downloading but it won't work.
I tried to call it with:
```
engine.remove()
```
and it returns:
```
node_modules\torrent-stream\index.js:718
        cb()
        ^

TypeError: cb is not a function
    at FSReqWrap.oncomplete (C:\Users\...\node_modules\torrent-stream\index.js:718:9)
```

I tried also
```
engine.remove([], function() {
    console.log("removed");
});
```
or
```
engine.remove(function() {
    console.log("removed");
});
```
and nothing happens, like I've never called this method. Is it possible that something is wrong there in the library?
Thank you :)

**Comment by mafintosh** [comment]
Did you fix this? :)

**Comment by giacomocerquone** [comment]
I don't think it was actually a problem of the library but a strange behaviour. In fact calling engine.remove the file were deleted but the swarm continued to download stuff (and I didn't even know where this stuff were downloaded).
So I fixed this calling engine.destroy() for first and engine.remove() right after.

**Comment by mafintosh** [comment]
Oh okay. I guess .remove should call .destroy for you. If you wanna PR that I'd merge it.

**Comment by giacomocerquone** [comment]
Ok, give me some time please because I would like also to check that callback and make it an optional paramater if it is ok for you.

**Comment by mafintosh** [comment]
Sounds good
