### ISSUE TITLE
Feature request: HTTP server

### ISSUE THREAD

**Issue by tsoernes** [mafintosh/torrent-stream#149]
For serving the content of the torrent that's being downloaded. Like peerflix uses and like Webtorrent has.

**Comment by rom1504** [comment]
you can use peerflix as a lib

**Comment by tsoernes** [comment]
Can you give an example?

**Comment by rom1504** [comment]
https://github.com/xat/castnow/blob/master/plugins/torrent.js#L23

**Comment by tsoernes** [comment]
`var engine = peerflix(torrent, opts);` takes the same opts as torrent-stream, right?

**Comment by rom1504** [comment]
yes https://github.com/mafintosh/peerflix/blob/master/index.js#L184

**Comment by tsoernes** [comment]
Thanks!

Issue closed.
