### ISSUE TITLE
cannot find module "hat"

### ISSUE THREAD

**Issue by MylesBorins** [mafintosh/torrent-stream#155]
node v5.3.0
npm 3.3.12

after `npm install` 
running ``npm ls` is returning 

```
npm ERR! missing: hat@0.0.3, required by torrent-stream@1.0.2
npm ERR! missing: bencode@^0.7.0, required by parse-torrent-file@2.1.4
npm ERR! missing: bittorrent-tracker@^7.0.0, required by torrent-discovery@5.2.0
npm ERR! missing: bencode@^0.7.0, required by bittorrent-dht@6.2.0
npm ERR! missing: bencode@^0.7.0, required by k-rpc-socket@1.4.3
```

**Comment by TheAlphaNerd** [comment]
looks like a problem with npm, but it is consistently failing the same way. I'm going to try testing master on v4 and try testing the last semver release to see if there is something special about the current setup

**Comment by TheAlphaNerd** [comment]
node v4.2.4
npm 2.14.12

Works as expected

**Comment by TheAlphaNerd** [comment]
torrent-stream v1.0.0 passes on node v5.4.0 with npm 3.3.12

**Comment by TheAlphaNerd** [comment]
v1.0.1 pass on the same setup as above

**Comment by TheAlphaNerd** [comment]
I opened https://github.com/npm/npm/issues/11062 to discuss this.

**Comment by iamblinking** [comment]
sudo npm install hat

**Comment by MylesBorins** [comment]
this was fixed a while back. fwiw the solution is most definitely not using sudo to install the module
