### ISSUE TITLE
question: seeding behind NAT/CGN(Carrier Grade NAT)

### ISSUE THREAD

**Issue by elBarkey** [mafintosh/torrent-stream#156]
Hi, so i spent my last 2 days to learn about hole punching.
From what i've learned, a device  with 3G/4G connected network is impossible to receive any inbound connection.
But in torrent-stream, seeding/uploading works on 3G/4G network.
Can you guys please explain how it works here ?

Thanks, el.

**Comment by bsuh** [comment]
You can still make outbound connections and seed through those.

**Comment by elBarkey** [comment]
Ahh.. I got it..
So the logical implementation is torrent client behind CGN acting as client instead of server while they were seeding.

thank you.

**Comment by sindhus** [comment]
> So the logical implementation is torrent client behind CGN acting as client instead of server while they were seeding.

Sorry I am butting in this conversation with a question that's not directly related to the repo itself but what @elBarkey said caught my attention. I am behind a Carrier Grade NAT ISP and was looking for a way to seed my torrents. Can Peerflix or torrent-stream that powers it help me seed?

Thanks!
