### ISSUE TITLE
confusing code??

### ISSUE THREAD

**Issue by wjianwei126** [mafintosh/torrent-stream#169]
it seems the code in exchangemeta.js  is not doing anything meaningful

for (var i = 0; i * METADATA_BLOCK_SIZE < size; i++) {
        if (metadataPieces[i]) continue
        wire.extended(channel, {msg_type: 0, piece: i})
      }

could someone elaberate on whats going on here? thanks

**Comment by asapach** [comment]
My guess is that it's requesting missing metadata pieces: http://www.bittorrent.org/beps/bep_0009.html

**Comment by wjianwei126** [comment]
ur right ~ I got it thanks

**Comment by amilajack** [comment]
Should this issue be closed?
