### ISSUE TITLE
private trackers

### ISSUE THREAD

**Issue by smolleyes** [mafintosh/torrent-stream#81]
hi

can we have small infos on why peerflix or torrent-stream can t use private trackers?

just tried acestream and it play everything!  private trackers or not

thanks :)

**Comment by lperennou** [comment]
hello guys, 

I still have the problems of peerflix only finding 1 peer with a private tracker. It finds much more on opened trackers. Do you have any ideas why ?

**Comment by smolleyes** [comment]
hi

if you use read-torrent to parse your torrent, try passing the raw 
object to torrent-stream not the torrent

exemple:

rTorrent(link, function(err, torrent, *raw*) {

do not pass torrent but raw to torrent-stream... it fixed the problem for me

++

**Comment by lperennou** [comment]
Thank you for the answer @smolleyes . I was trying to use peerflix with the command line on Linux. 
But I can't send the output of read-torrent to peerflix this way, right ? I tried : 

read-torrent my.torrent > mytorrent 
peerflix mytorrent --vlc

Should I write a nodejs program to read the torrent file and launch peeflix like you advised ?

**Comment by pastudan** [comment]
In my case, the tracker that I use block certain torrent clients from receiving peers. I'd reach out to your tracker's admins and ask that they whitelist peerflix, but in the meantime a way of testing is to spoof the peer id and user agent. Be careful doing this as most have rules that prohibit this. They also needed a parameter called `left`, which is how many bytes you have remaining to download.

You might want to modify the torrent-stream library to take in a peerId and userAgent from your opts.

```js
  var discovery = peerDiscovery({
    port: DEFAULT_PORT,
    announce: opts.trackers,
    infoHash: link.infoHash, // as hex string or Buffer
    peerId: new Buffer(opts.id),  // as hex string or Buffer
    dht: false, // use dht? optionally, this can be an `opts` object, or a DHT instance to use (can be reused for multiple torrents)
    userAgent: opts.userAgent, // User-Agent header for http requests
    tracker: {
      getAnnounceOpts: function () {
        return {
          // key: '' // I don't know what this is for, but my client sent it when I watched it connect to a tracker. Doesn't seem to be needed by my tracker though
          compact: '1',
          supportcrypto: '1',
          event: 'started',
          uploaded: '0',
          downloaded: '0',
          left: link.length,
        }
      }
    }
  })
```

Hope this helps
