### ISSUE TITLE
use load-ip-set

### ISSUE THREAD

**Issue by feross** [mafintosh/torrent-stream#85]
Just wanted to let you know about [load-ip-set](https://npmjs.org/package/load-ip-set) which offers a superset of the current blocklist functionality.

Let's keep unifying torrent-stream and webtorrent code!

**Comment by Coriou** [comment]
Hey. 

I'm using a project based on torrent-stream ([peerflix-server](https://github.com/asapach/peerflix-server)) and I'd like to implement blocklist support there. The way blocklist is currently implemented in torrent-stream requires the user to pass in a single range of IP on engine load on add IPs one by one to the set which is inconvenient in many cases.

Was thinking about implementing this at the application level, in my case Peerflix Server (as discussed there https://github.com/asapach/peerflix-server/issues/173) but reading about this and the best way of doing it, I think it would make a lot of sense to just upgrade torrent-stream to use load-ip-set. This way, the blocklist system is much more effective and user friendly (just throw in a blocklist URL or file and you're good to go).

I can work on it, it's really a minor update, and it would benefit peerflix / peerflix-server too.

**Comment by feross** [comment]
I'm extremely strapped for time and can't implement this, so I'm closing this.
