### ISSUE TITLE
question: send js blob to torrent-stream

### ISSUE THREAD

**Issue by smolleyes** [mafintosh/torrent-stream#86]
hi

i have some difficulties to download and write torrents from a private tracker to file (or buffer) and pass it to torrent-stream...

i can get a blob of my torrent thru $ajax 

Blob {type: "application/x-bittorrent", size: 14462, slice: function}

how can i do to convert / use this blob with torrent-stream :/ ?

thanks

**Comment by jaruba** [comment]
How did you ever get this working smolleyes?

I think I tried all I can think of.. tried decoding ```iso-8859-1``` to ```utf-8``` with ```iconv-lite```, saving to files (only ```binary``` and ```ascii`` worked, but torrent-stream finds the wrong hash if it reads it in this encoding), sending as array buffers, UInt8Array buffers, tried ```XMLHttpRequest```, ```node-request``` and ```node-http```.

If it's a ```UInt8Array``` I get the error that it's not a torrent or magnet link. If it's anything else and re-encoded to ```binary``` or ```ascii```, it says that some character at point ... is wrong.

**Comment by mafintosh** [comment]
@jaruba torrents are binary files. if you have trouble getting this to work you can generate a magnet link instead by doing `magnet:?xt=urn:sha1:{infohash}`

**Comment by jaruba** [comment]
Then shouldn't this work:

	var request = require("request");
	var requestOptions  = { encoding: null, url: torLink};
	
	request(requestOptions, function(error, response, body) {
		peerflix("magnet:\?xt=urn:sha1:"+require('crypto').createHash('sha1').update(body).digest('hex'));	
	});

But I'm getting:
```Uncaught Error: You must pass a valid torrent or magnet link - peerflix/node_modules/torrent-stream/index.js:69```

**Comment by asapach** [comment]
Shouldn't it be `magnet:?xt=urn:btih:{infoHash}` instead of `magnet:?xt=urn:sha1:{infohash}`?

**Comment by asapach** [comment]
Also @jaruba, you should probably use [read-torrent](https://www.npmjs.com/package/read-torrent) for what you're trying to do.

**Comment by jaruba** [comment]
This worked great:

	var readTorrent = require('read-torrent');
	 
	readTorrent(torLink, function(err, torrent) {
		peerflix("magnet:\?xt=urn:btih:"+torrent["infoHash"]);
	});

If I only knew about this 24 hours ago.. Thanks a lot. :)

**Comment by asapach** [comment]
You can just pass the torrent:

```js
var readTorrent = require('read-torrent');

readTorrent(torLink, function(err, torrent) {
    peerflix(torrent);
});
```

**Comment by jaruba** [comment]
Even better, thanks. :)
