### ISSUE TITLE
Problem with connection to wires

### ISSUE THREAD

**Issue by Kureev** [mafintosh/torrent-stream#92]
Hi @mafintosh ,
I'm wondering if you can explain (or show me where to find it) the difference between torrent-stream and uTorrent (for example) connection mechanism. Sometime torrent-stream (and peerflix) unable to start streaming. As i understood, the problem is that all of the wires are choked. Can you tell me why it happens and does it possible to avoid it somehow?

**Comment by wiebemarten** [comment]
"private" torrents mean that only select people can use/know of a certain tracker. I think that as soon as you provide a tracker to the custom tracker list of the torrent-stream options, it should be able to download it.

**Comment by jaruba** [comment]
I'm having a similar issue, I use peerflix (obviously with torrent-stream) in node-webkit, and if the engine is dorment for a while, it disconnects all peers and does not download anymore if I ```.select()`` a file or try to access a http stream.

```.swarm.wires.length``` returns 0, how can I restart a peer check?
