### ISSUE TITLE
Dependably get send/receive speed in mbps

### ISSUE THREAD

**Issue by acidhax** [mafintosh/torrent-stream#96]
How would one calculate the current download mbps and upload mbps?

**Comment by asapach** [comment]
A `torrent-stream` instance has a [`swarm`](https://github.com/mafintosh/torrent-stream#engineswarm) property, which in turn has [`downloadSpeed()` and `uploadSpeed()` methods](https://github.com/mafintosh/peer-wire-swarm/blob/885577b3ff03f90510fe2dc310f37a45e544e3ab/index.js#L155).

**Comment by mafintosh** [comment]
Like @asapach said use the swarm. If for some reason you have trouble getting this to work feel free to reopen.
