### ISSUE TITLE
question: How to stream a torrent file

### ISSUE THREAD

**Issue by herlon214** [mafintosh/torrent-stream#97]
How do I stream a torrent file? I saw only magnet.

Thanks in advance.

**Comment by mafintosh** [comment]
Just pass the contents of the torrent file as a buffer

``` js
var buf = fs.readFileSync('my.torrent')
var engine = torrentStream(buf)
```

**Comment by herlon214** [comment]
Thanks for the response.

2015-02-18 6:22 GMT-03:00 Mathias Buus <notifications@github.com>:

> Just pass the contents of the torrent file as a buffer
>
> var buf = fs.readFileSync('my.torrent')var engine = torrentStream(buf)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mafintosh/torrent-stream/issues/97#issuecomment-74834743>
> .
>



-- 
*Att, Herlon Aguiar*
